services:
  worldboss-bot:
    build:
      context: ../worldboss-app
      dockerfile: deployment/Dockerfile
    restart: unless-stopped
    env_file:
      - ../worldboss-app/.env
    depends_on:
      - worldboss-db
      - worldboss-redis

  worldboss-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - worldboss_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: worldboss
      POSTGRES_PASSWORD: worldboss
      POSTGRES_DB: worldboss

  worldboss-redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - worldboss_redis:/data

volumes:
  worldboss_postgres:
  worldboss_redis:
